project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
pull_request_title: 'chore: New Crowdin translations to review and merge'
pull_request_body: '### What\n- Automated pull request pulling in new or updated translations from Crowdin (https://translate.openfoodfacts.org).\n## Checklist\n- [ ] Check that they are no bad translations. If there are, correct them directly in Crowdin so that they are not resynced again. Then you can correct them here as well, or wait 24 hours for the sync to happen automatically.\n- [ ] Put extra attention on Acholi, which is used mistakenly as a sandbox by people discovering the self-service translation button on Open Food Facts\n- [ ] Once you are happy, that automated checks pass, you can approve the PR and merge it.\n### Part of\n- Translations'
files:
  - source: /blog/join-our-worldwide-collaborative-effort-to-collect-info-on-the-packaging-of-food.html
    translation: /blog/%locale%/join-our-worldwide-collaborative-effort-to-collect-info-on-the-packaging-of-food.html
  - source: /blog/a-clever-device-to-photograph-tins.html
    translation: /blog/%locale%/a-clever-device-to-photograph-tins.html
  - source: /blog/discover-the-5 colors-A-B-C-D-E-nutrition-grade-of-X-country-products-on-openfoodfacts.html
    translation: /blog/%locale%/discover-the-5 colors-A-B-C-D-E-nutrition-grade-of-X-country-products-on-openfoodfacts.html
  - source: /blog/graphs-in-3-clicks.html
    translation: /blog/%locale%/graphs-in-3-clicks.html
  - source: /blog/introducing-open-products-facts-all-your-product-are-belong-to-us.html
    translation: /blog/%locale%/introducing-open-products-facts-all-your-product-are-belong-to-us.html
  - source: /blog/launch-of-open-food-facts-join-the-food-revolution.html
    translation: /blog/%locale%/launch-of-open-food-facts-join-the-food-revolution.html
  - source: /blog/made-near-eu-and-makes-you-curious.html
    translation: /blog/%locale%/made-near-eu-and-makes-you-curious.html
  - source: /blog/open-and-linked-data-rdf-export-of-data.html
    translation: /blog/%locale%/open-and-linked-data-rdf-export-of-data.html
  - source: /blog/scanning-is-already-contributing.html
    translation: /blog/%locale%/scanning-is-already-contributing.html
  - source: /blog/support-open-food-facts-on-helloasso-and-lilo-and-be-a-part-the-hosting-of-the-project.html
    translation: /blog/%locale%/support-open-food-facts-on-helloasso-and-lilo-and-be-a-part-the-hosting-of-the-project.html
  - source: /blog/how-many-different-food-products-are-there-in-the-world.html
    translation: /blog/%locale%/how-many-different-food-products-are-there-in-the-world.html
  - source: /blog/advanced-search-form-and-data-export.html
    translation: /blog/%locale%/advanced-search-form-and-data-export.html
  - source: /blog/wrapping-it-up.html
    translation: /blog/%locale%/wrapping-it-up.html
  - source: /blog/mailing-nutriscore.html
    translation: /blog/%locale%/mailing-nutriscore.html
  - source: /blog/new-mobile-app-2019.html
    translation: /blog/%locale%/new-mobile-app-2019.html
  - source: /blog/mailing-newapp.html
    translation: /blog/%locale%/mailing-newapp.html
  - source: /blog/1-million-products.html
    translation: /blog/%locale%/1-million-products.html
  - source: /blog/real-time-product-data-from-producers.html
    translation: /blog/%locale%/real-time-product-data-from-producers.html
  - source: /blog/days-off-2022.html
    translation: /blog/%locale%/days-off-2022.html
  - source: /blog/agena-3000.html
    translation: /blog/%locale%/agena-3000.html
  - source: /blog/ecoscore-launch.html
    translation: /blog/%locale%/ecoscore-launch.html
  - source: /blog/personal-search.html
    translation: /blog/%locale%/personal-search.html
  - source: /blog/taxonomies-by-yukti.html
    translation: /blog/%locale%/taxonomies-by-yukti.html
  - source: /blog/operation-toothpaste.html
    translation: /blog/%locale%/operation-toothpaste.html
  - source: /blog/what-happened-at-the-open-food-facts-days-22.html
    translation: /blog/%locale%/what-happened-at-the-open-food-facts-days-22.html
  - source: /blog/meeting-more-than-400-producers-in-2-days-its-possible-thanks-to-sial.html
    translation: /blog/%locale%/meeting-more-than-400-producers-in-2-days-its-possible-thanks-to-sial.html
  - source: /blog/how-open-food-facts-can-help-reduce-waste-and-improve-recycling.html
    translation: /blog/%locale%/how-open-food-facts-can-help-reduce-waste-and-improve-recycling.html
  - source: /blog/opening-the-honeypot.html
    translation: /blog/%locale%/opening-the-honeypot.html
  - source: /blog/presenting-open-food-facts-at-events-a-case-study.html
    translation: /blog/%locale%/presenting-open-food-facts-at-events-a-case-study.html
  - source: /blog/open-food-facts-is-getting-a-makeover.html
    translation: /blog/%locale%/open-food-facts-is-getting-a-makeover.html
  - source: /blog/there-is-no-age-limit-for-a-packaging-workshop.html
    translation: /blog/%locale%/there-is-no-age-limit-for-a-packaging-workshop.html
  - source: /blog/operation-packaging-announcement.html
    translation: /blog/%locale%/operation-packaging-announcement.html
  - source: /blog/our-producers-platform-is-getting-a-makeover.html
    translation: /blog/%locale%/our-producers-platform-is-getting-a-makeover.html
  - source: /blog/feedback-from-people-who-are-weighing-in-on-the-tackling-packaging-operation.html
    translation: /blog/%locale%/feedback-from-people-who-are-weighing-in-on-the-tackling-packaging-operation.html
  - source: /blog/the-agribalyse-3-1-update-and-its-impact-on-the-eco-score-in-open-food-facts.html
    translation: /blog/%locale%/the-agribalyse-3-1-update-and-its-impact-on-the-eco-score-in-open-food-facts.html
  - source: /blog/discussions-on-a-harmonised-ecolabel-at-european-level-the-debate-is-moving-forward.html
    translation: /blog/%locale%/discussions-on-a-harmonised-ecolabel-at-european-level-the-debate-is-moving-forward.html
  - source: /blog/how-open-food-facts-uses-logos-to-get-information-on-food-products.html
    translation: /blog/%locale%/how-open-food-facts-uses-logos-to-get-information-on-food-products.html
  - source: /blog/organise-a-scan-party-participative-workshop.html
    translation: /blog/%locale%/organise-a-scan-party-participative-workshop.html
  - source: /blog/we-go-green-2-days-in-berlin-for-the-international-green-week.html
    translation: /blog/%locale%/we-go-green-2-days-in-berlin-for-the-international-green-week.html
  - source: /blog/pages/join-the-tackling-food-packaging-operation.html
    translation: /blog/%locale%/pages/join-the-tackling-food-packaging-operation.html
  - source: blog/en-US/testimonial-the-win-win-partnership-between-mylabel-and-open-food-facts.html
    translation: /blog/%locale%/pages/testimonial-the-win-win-partnership-between-mylabel-and-open-food-facts.html
  - source: blog/en-US/towards-1-million-users-and-beyond-for-open-food-facts-mobile-app.html
    translation: /blog/%locale%/pages/towards-1-million-users-and-beyond-for-open-food-facts-mobile-app.html
  - source: blog/en-US/italia-here-we-come-a-look-back-at-our-presence-at-cibus-parma.html
    translation: /blog/%locale%/pages/italia-here-we-come-a-look-back-at-our-presence-at-cibus-parma.html
  - source: blog/en-US/a-contributors-story.html
    translation: /blog/%locale%/pages/a-contributors-story.html
  - source: blog/Using-the-Open-Food-Facts-app-to-accompany-scientific-research-yes-we-scan.html
    translation: /blog/%locale%/Using-the-Open-Food-Facts-app-to-accompany-scientific-research-yes-we-scan.html
